### ISSUE TITLE
Build failure because of HttpClient

### ISSUE THREAD

**Issue by hfiguiere** [ktgw0316/LightZone#390]
**Describe the bug**
Build fail because of HttpClient not inplementing AutoCloseable

**To Reproduce**
1. Build ligthzone

**Expected behavior**
Build is successfull

**Screenshots**
```
    [javac] Compiling 1038 source files to /run/build/lightzone/lightcrafts/build/classes/java/main
    [javac] /run/build/lightzone/lightcrafts/src/main/java/com/lightcrafts/app/CheckForUpdate.java:276: error: incompatible types: try-with-resources not applicable to variable type
    [javac]         try (final var client = HttpClient.newHttpClient()) {
    [javac]                        ^
    [javac]     (HttpClient cannot be converted to AutoCloseable)
```

In addition to the error in #389 

**Desktop (please complete the following information):**
 - Version 5.0.0
 - OS: Linux (Flatpak)
 - Java: jdk-21.0.11+10

**Additional context**
Regression from commit 4bf627d1c85b079db8bbe56df64943a4454e080c

**Comment by ktgw0316** [comment]
@hfiguiere HttpClient does inplement AutoCloseable since JDK21. Could you show me the output of `javac -version` and `echo $JAVA_HOME`?

**Comment by hfiguiere** [comment]
```
javac 21.0.11
/usr/lib/sdk/openjdk21/jvm/openjdk-21
```

**Comment by ktgw0316** [comment]
I found that this is a flatpak's issue.  I'm going to send a PR for flathub in this weekend.

P. S. @hfiguiere You already made a [draft PR](https://github.com/flathub/io.github.ktgw0316.LightZone/pull/2), so I'll add some comments on it.

**Comment by hfiguiere** [comment]
It's because build.xml still say Java 17. See #391 for a fix. 
(can't use gradle)
