### ISSUE TITLE
Build failure because of Math.clamp

### ISSUE THREAD

**Issue by hfiguiere** [ktgw0316/LightZone#389]
**Describe the bug**
Lightzone fail to build because of Math.clamp()

**To Reproduce**
1. build Lightzone
2. 
**Expected behavior**
Builds

**Screenshots**
```
    [javac] Compiling 1038 source files to /run/build/lightzone/lightcrafts/build/classes/java/main
    [javac] /run/build/lightzone/lightcrafts/src/main/java/com/lightcrafts/model/ImageEditor/WhitePointOperationImpl.java:152: error: cannot find symbol
    [javac]                     table[0][i] = (short) (0xffff & (int) Math.clamp(i + 0xff * interpolator.interpolate(i / (double) 0xffff, redCurve), 0, 0xffff));
    [javac]                                                               ^
    [javac]   symbol:   method clamp(double,int,int)
    [javac]   location: class Math
    [javac] /run/build/lightzone/lightcrafts/src/main/java/com/lightcrafts/model/ImageEditor/WhitePointOperationImpl.java:156: error: cannot find symbol
    [javac]                     table[1][i] = (short) (0xffff & (int) Math.clamp(i + 0xff * interpolator.interpolate(i / (double) 0xffff, greenCurve), 0, 0xffff));
    [javac]                                                               ^
    [javac]   symbol:   method clamp(double,int,int)
    [javac]   location: class Math
    [javac] /run/build/lightzone/lightcrafts/src/main/java/com/lightcrafts/model/ImageEditor/WhitePointOperationImpl.java:160: error: cannot find symbol
    [javac]                     table[2][i] = (short) (0xffff & (int) Math.clamp(i + 0xff * interpolator.interpolate(i / (double) 0xffff, blueCurve), 0, 0xffff));
    [javac]                                                               ^
    [javac]   symbol:   method clamp(double,int,int)
    [javac]   location: class Math
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
```

**Desktop (please complete the following information):**
 - Version: 5.0.0
 - OS: Linux (Flatpak)
 - Java: jdk-21.0.11+10

**Additional context**

**Comment by hfiguiere** [comment]
Change was introduced in commit 4cf9b423461c7bc1eaff312ab01a4f64e9fef7e0

**Comment by hfiguiere** [comment]
Note: I reverted commit 4bf627d1c85b079db8bbe56df64943a4454e080c first, see #390
